export const ProductErrors = {
	NOT_FOUND_BY_ID: 'Товар с таким id не найден.',
	NOT_FOUND_BY_SLUG: 'Товар с таким slug не найден.',
	NOT_FOUND_BY_TITLE: 'Товар с таким title не найден.',
	TITLE_MUST_BE_STRING: 'Title должен быть строкой.',
	SLUG_MUST_BE_STRING: 'Slug должен быть строкой.',
	PRICE_MUST_BE_NUMBER: 'Цена должна быть числом.',
	META_TITLE_MUST_BE_STRING: 'MetaTitle должен быть строкой.',
	META_DESC_MUST_BE_STRING: 'MetaDesc должен быть строкой.',
	SEO_TEXT_MUST_BE_STRING: 'SeoText должен быть строкой.',
	CATEGORY_ID_MUST_BE_NUMBER: 'CategoryId должен быть числом.',
	CATEGORY_NOT_FOUND: 'Категория не найдена.',
	SIZE_IDS_MUST_BE_ARRAY_OF_NUMBERS: 'SizeIds должен быть массивом чисел.',
	COLOR_IDS_MUST_BE_ARRAY_OF_NUMBERS: 'ColorIds должен быть массивом чисел.',
	ALLREADY_EXIST: 'Товар с таким title уже существует.',
	DISCONT_MUST_BE_NUMBER: 'Discont должен быть числом.',
	IMAGES_MUST_BE_ARRAY: 'Images должен быть массивом строк.',
	TAGS_MUST_BE_ARRAY: 'Tags должен быть массивом строк.',
	COLORSIDS_NOT_FOUND: '1 или более цветов не найдено.',
	SIZESIDS_NOT_FOUND: '1 или более размеров не найдено.',
	MIN_PRICE_MUST_BE_NUMBER: 'MinPrice должен быть числом.',
	MAX_PRICE_MUST_BE_NUMBER: 'MaxPrice должен быть числом.',
	PAGE_MUST_BE_NUMBER: 'Page должен быть числом.',
	LIMIT_MUST_BE_NUMBER: 'Limit должен быть числом.',
	NOT_FOUND: 'Товары не найден.',
};
