export const ProductErrors = {
	NOT_FOUND_BY_ID: 'Product with this id not found',
	NOT_FOUND_BY_SLUG: 'Product with this slug not found',
	NOT_FOUND_BY_TITLE: 'Product with this title not found',
	TITLE_MUST_BE_STRING: 'Product title must be a string',
	SLUG_MUST_BE_STRING: 'Product slug must be a string',
	PRICE_MUST_BE_NUMBER: 'Product price must be a number',
	META_TITLE_MUST_BE_STRING: 'Product MetaTitle must be a string',
	META_DESC_MUST_BE_STRING: 'Product MetaDescription must be a string',
	SEO_TEXT_MUST_BE_STRING: 'Product SeoText must be a string',
	CATEGORY_ID_MUST_BE_NUMBER: 'Category ID must be a number',
	CATEGORY_NOT_FOUND: 'Category not found',
	SIZE_IDS_MUST_BE_ARRAY_OF_NUMBERS: 'SizeIDS must be an array of numbers',
	COLOR_IDS_MUST_BE_ARRAY_OF_NUMBERS: 'ColorIDS must be an array of numbers',
	ALLREADY_EXIST: 'Product with this title already exists',
	DISCONT_MUST_BE_NUMBER: 'Discount must be a number.',
	IMAGES_MUST_BE_ARRAY: 'Images must be an array of strings.',
	TAGS_MUST_BE_ARRAY: 'Tags must be an array of strings.',
	COLORSIDS_NOT_FOUND: '1 or more colorIDs not found.',
	SIZESIDS_NOT_FOUND: '1 or more sizeIDs not found.',
	MIN_PRICE_MUST_BE_NUMBER: 'MinPrice must be a number.',
	MAX_PRICE_MUST_BE_NUMBER: 'MaxPrice must be a number.',
	PAGE_MUST_BE_NUMBER: 'Page must be a number.',
	LIMIT_MUST_BE_NUMBER: 'Limit must be a number.',
	NOT_FOUND: 'Product not found',
	INVALID_PARAMS: 'Invalid params - page and/or limit.',
	NOT_FOUND_BY_CATEGORY_ID: 'Product not found by category ID',
};
